In [1]:
import numpy as np

In [2]:
I = complex(0, 1)
Pi = np.pi

In [3]:
angle = 90
delta = angle * (np.pi / 180)

In [4]:
K20 = 1 / 0.9
K2 = 1/0.4
K_steps = 10
K = np.arange(K20, K2+(K2-K20)/K_steps, (K2-K20)/K_steps)

In [5]:
'''
pitch=0.4533
L1 = 3
L2 = 2

Q_N_pitch1 = 165
Q_N_pitch2 = 110
N_pitch1 = L1 / pitch
N_pitch2 = L2 / pitch

Q1 = Q_N_pitch1 / N_pitch1
Q2 = Q_N_pitch2 / N_pitch2
'''

'\npitch=0.4533\nL1 = 3\nL2 = 2\n\nQ_N_pitch1 = 165\nQ_N_pitch2 = 110\nN_pitch1 = L1 / pitch\nN_pitch2 = L2 / pitch\n\nQ1 = Q_N_pitch1 / N_pitch1\nQ2 = Q_N_pitch2 / N_pitch2\n'

In [6]:
'''
NoC = 1.42
NeC = 1.57
'''

'\nNoC = 1.42\nNeC = 1.57\n'

In [7]:
#Fo = np.exp(I*2*Pi*K*pitch/Q1*NoC)

In [8]:
def T1_matrix(K, pitch, Q_N_pitch1, L1, NoC, NeC):   
    
    N_pitch1 = L1 / pitch
    Q1 = Q_N_pitch1 / N_pitch1
    
    delta = 2 * np.pi / Q1
    
    Fo = np.exp(I*2*Pi*K*pitch/Q1*NoC)
    Fe = np.exp(I*2*Pi*K*pitch/Q1*NeC)
    
    No = NoC
    Ne = NeC
    
    T1 = np.zeros((4, 4))

    T1[0][0] = np.cos(delta)/Fo 
    T1[0][1] = 0
    T1[0][2] = -(1/2)*np.sin(delta)*(No+Ne)/(No*Fe)
    T1[0][3] = (1/2)*Fe*np.sin(delta)*(-No+Ne)/No

    T1[1][0] = 0
    T1[1][1] = Fo*np.cos(delta) 
    T1[1][2] = (1/2)*np.sin(delta)*(-No+Ne)/(No*Fe) 
    T1[1][3] = -(1/2)*Fe*np.sin(delta)*(No+Ne)/No

    T1[2][0] = (1/2)*np.sin(delta)*(No+Ne)/(Ne*Fo) 
    T1[2][1] = (1/2)*Fo*np.sin(delta)*(-No+Ne)/Ne 
    T1[2][2] = np.cos(delta)/Fe 
    T1[2][3] = 0

    T1[3][0] = (1/2)*np.sin(delta)*(-No+Ne)/(Ne*Fo) 
    T1[3][1] = (1/2)*Fo*np.sin(delta)*(No+Ne)/Ne 
    T1[3][2] = 0 
    T1[3][3] = Fe*np.cos(delta)
    
    return T1

In [9]:
def T2_matrix(K, pitch, Q_N_pitch2, L2, NoC, NeC):   
    
    N_pitch2 = L2 / pitch
    Q2 = Q_N_pitch2 / N_pitch2
    
    delta = 2 * np.pi / Q2
    
    Fo = np.exp(I*2*Pi*K*pitch/Q2*NoC)
    Fe = np.exp(I*2*Pi*K*pitch/Q2*NeC)
    
    No = NoC
    Ne = NeC
    
    T2 = np.zeros((4, 4))

    T2[0][0] = np.cos(delta)/Fo 
    T2[0][1] = 0
    T2[0][2] = -(1/2)*np.sin(delta)*(No+Ne)/(No*Fe)
    T2[0][3] = (1/2)*Fe*np.sin(delta)*(-No+Ne)/No

    T2[1][0] = 0
    T2[1][1] = Fo*np.cos(delta) 
    T2[1][2] = (1/2)*np.sin(delta)*(-No+Ne)/(No*Fe) 
    T2[1][3] = -(1/2)*Fe*np.sin(delta)*(No+Ne)/No

    T2[2][0] = (1/2)*np.sin(delta)*(No+Ne)/(Ne*Fo) 
    T2[2][1] = (1/2)*Fo*np.sin(delta)*(-No+Ne)/Ne 
    T2[2][2] = np.cos(delta)/Fe 
    T2[2][3] = 0

    T2[3][0] = (1/2)*np.sin(delta)*(-No+Ne)/(Ne*Fo) 
    T2[3][1] = (1/2)*Fo*np.sin(delta)*(No+Ne)/Ne 
    T2[3][2] = 0 
    T2[3][3] = Fe*np.cos(delta)
    
    return T2

In [10]:
def TD_matrix(K, Ld, Nd, NoC, NeC):
    delta = 0
    
    FeD = np.exp(I*2*Pi*K*Ld*Nd)
    Fo = FeD
    Fe = FeD
    
    N0 = (NoC + NeC) / 2
    
    No = N0
    Ne = N0
    
    TD = np.zeros((4, 4))

    TD[0][0] = np.cos(delta)/Fo 
    TD[0][1] = 0
    TD[0][2] = -(1/2)*np.sin(delta)*(No+Ne)/(No*Fe)
    TD[0][3] = (1/2)*Fe*np.sin(delta)*(-No+Ne)/No

    TD[1][0] = 0
    TD[1][1] = Fo*np.cos(delta) 
    TD[1][2] = (1/2)*np.sin(delta)*(-No+Ne)/(No*Fe) 
    TD[1][3] = -(1/2)*Fe*np.sin(delta)*(No+Ne)/No

    TD[2][0] = (1/2)*np.sin(delta)*(No+Ne)/(Ne*Fo) 
    TD[2][1] = (1/2)*Fo*np.sin(delta)*(-No+Ne)/Ne 
    TD[2][2] = np.cos(delta)/Fe 
    TD[2][3] = 0

    TD[3][0] = (1/2)*np.sin(delta)*(-No+Ne)/(Ne*Fo) 
    TD[3][1] = (1/2)*Fo*np.sin(delta)*(No+Ne)/Ne 
    TD[3][2] = 0 
    TD[3][3] = Fe*np.cos(delta)
    
    return TD

In [ ]:
def RmL1_Matrix():

In [11]:
print(f' T1: \n {T1_matrix(1, 0.4533, 165, 3, 1.42, 1.57)} \n')
print(f' T2: \n {T2_matrix(1, 0.4533, 110, 2, 1.42, 1.57)} \n')
print(f' TD: \n {TD_matrix(1, 0.1197, 1.42+0.0075j, 1.42, 1.57)} \n')

 T1: 
 [[ 0.95569703  0.         -0.25831771  0.01295908]
 [ 0.          0.95569703  0.01295908 -0.25831771]
 [ 0.23432921  0.01175565  0.95287664  0.        ]
 [ 0.01175565  0.23432921  0.          0.95287664]] 

 T2: 
 [[ 0.95569703  0.         -0.25831771  0.01295908]
 [ 0.          0.95569703  0.01295908 -0.25831771]
 [ 0.23432921  0.01175565  0.95287664  0.        ]
 [ 0.01175565  0.23432921  0.          0.95287664]] 

 TD: 
 [[0.48462275 0.         0.         0.        ]
 [0.         0.47918623 0.         0.        ]
 [0.         0.         0.48462275 0.        ]
 [0.         0.         0.         0.47918623]] 



C:\Users\diter\AppData\Local\Temp\ipykernel_38316\522032355.py:16: ComplexWarning: Casting complex values to real discards the imaginary part
  T1[0][0] = np.cos(delta)/Fo
C:\Users\diter\AppData\Local\Temp\ipykernel_38316\522032355.py:18: ComplexWarning: Casting complex values to real discards the imaginary part
  T1[0][2] = -(1/2)*np.sin(delta)*(No+Ne)/(No*Fe)
C:\Users\diter\AppData\Local\Temp\ipykernel_38316\522032355.py:19: ComplexWarning: Casting complex values to real discards the imaginary part
  T1[0][3] = (1/2)*Fe*np.sin(delta)*(-No+Ne)/No
C:\Users\diter\AppData\Local\Temp\ipykernel_38316\522032355.py:22: ComplexWarning: Casting complex values to real discards the imaginary part
  T1[1][1] = Fo*np.cos(delta)
C:\Users\diter\AppData\Local\Temp\ipykernel_38316\522032355.py:23: ComplexWarning: Casting complex values to real discards the imaginary part
  T1[1][2] = (1/2)*np.sin(delta)*(-No+Ne)/(No*Fe)
C:\Users\diter\AppData\Local\Temp\ipykernel_38316\522032355.py:24: ComplexWarning: